### PR TITLE
Fixed incorrect api endpoint and added access to VITE_BACKEND_URL stored in .env

### PR DESCRIPTION
**Pull request by michaelphipps**
I needed to correct some of the api endpoints before I could make this work on my system.  This pull request contains those changes.

I've also added a way to securely access the VITE_BACKEND_URL variable from the .env file.

### CODE REVIEW

**Comment by lindgr3n** [comment]
Thanks for trying this out! These changes will make the frontend talk directly with the Laravel backend. I use two instances of Axios so the frontend uses one to talk to the SvelteKit endpoints. And the other to talk with the Laravel Backend.
That's why `src/lib/axios.ts` do not have any `baseURL` so it uses localhost:3000. All calls from the client uses `/api/` so we call the SvelteKIt endpoints.

What error do you get using the original code?

**Comment by michaelphipps** [comment]
> What error do you get using the original code?

I couldn't register, and I was getting 404 errors returned from api calls.

> Thanks for trying this out! These changes will make the frontend talk directly with the Laravel backend. I use two instances of Axios so the frontend uses one to talk to the SvelteKit endpoints. And the other to talk with the Laravel Backend. That's why `src/lib/axios.ts` do not have any `baseURL` so it uses localhost:3000. All calls from the client uses `/api/` so we call the SvelteKIt endpoints.
> 

This is literally the first time I've used SvelteKit and Laravel.  

SvelteKit -> Laravel makes perfect sense to me.

So it reads to me like the api calls are being made like this: SvelteKit -> SvelteKit  -> Laravel.  If that's the case, why?

**Comment by lindgr3n** [comment]
Hmm, what version of Laravel are you using? Running your own laravel application or using the other [repo](https://github.com/lindgr3n/breeze-backend-api) ? 

I'm still learning myself so good to get some questions :)

> So it reads to me like the api calls are being made like this: SvelteKit -> SvelteKit -> Laravel. If that's the case, why?

Yeah, exactly. The main reason is to serverside render the page before it is processed by the client.
E.g. in this basic example if we did not return the user from the `getSession` we would not be able to return it in the load method in `__layout` (That is run twice, once serverside and once clientside). In that case the page would have been rendered with no user name until we fetch it and it is updated.

E.g. if you change the `__layout` to 
```
<script>
	import '../app.css';
	import { user } from '$lib/store/user';
	import { authClient } from '$lib/axios_backend';
	import { onMount } from 'svelte';

	export let userSession;

	if (userSession) {
		// user.set(userSession);
	}

	onMount(async () => {
		const response = await authClient('/api/user');
		user.set(response.data);
	});
</script>
```

You will notice we get a few ms where the name is missing until it is set :)

Another approach would be to make use of the client load to fetch the user before the component is created. So we could update the context

```
<script context="module">
	export async function load({ url, session }) {
		const { authenticated, guest } = session;
		let user = null;
		if (browser) {
			const response = await authClient('/api/user');
			user = response.data;
		}
		// If we are not on a guest endpoint and we are not authenticated we redirect
		if (!authenticated && !guest) {
			return {
				status: 302,
				redirect: '/login'
			};
		}

		return {
			status: 200,
			props: {
				userSession: user
			}
		};
	}
</script>
```
Note you need to wrap it inside the `browser` otherwise not correct headers are passed.

**Comment by michaelphipps** [comment]
I've taken a much closer look at the way this has been put together, and my PR doesn't actually fix some important issues at the core.  I am going to abandon this and use a different approach.  I'll try to remember to share what I come up with.

**Comment by michaelphipps** [comment]
meant to press close.

**Comment by lindgr3n** [comment]
Thanks for reaching out! Please if you remember (otherwise ill ping you ;) ) to share your findings. Just tag me on Twitter :) Would like to find more approaches for this.

**Pull request closed without merging**
